# General
device_preference: "cuda"
num_threads: 1
chunk_duration_sec: 300
output_suffix: "_diarized"
export_txt: true

# Models
segmentation_model: "/Users/gauravjain/Documents/work/exported-assets/models/sherpa-onnx-pyannote-segmentation-3-0/model.onnx"
embedding_extractor_model: "/Users/gauravjain/Downloads/nemo_en_speakerverification_speakernet.onnx"
whisper_model_id: "/Users/gauravjain/Downloads/prime"

# Diarization
num_speakers: 2
cluster_threshold: 0.5
min_duration_on: 0.1
min_duration_off: 0.1

# Audio
target_sample_rate: 16000
glob_audio_extensions: ["*.wav", "*.mp3", "*.flac"]

# ASR
asr_language: "en"
task: "transcribe"
